name: Release Docker Back

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  docker-release:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change versions
        uses: docker/login-action@v1
        with:
          repo: Anthony-Jhoiro/sample-deployments
          token: ${{ env.GITHUB_TOKEN }}
          # ref: 
          changes: '[{"path": "examples/my-deplyment", "service": "my-service", "image": "my-image:v123"}]'
          # slack-webhook
          commit-message: "Hello World"
