name: Release Docker Back

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write


jobs:
  docker-release:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change versions
        uses: Anthony-Jhoiro/docker-deploy-github-action@feat/action_basic
        with:
          repo: Anthony-Jhoiro/sample-deployments
          token: ${{ secrets.GITHUB_TOKEN }}
          # ref: 
          changes: '[{"path": "deployment", "service": "my-service", "image": "my-image:v123"}]'
          # slack-webhook
          commit-message: "Hello World"
